### PR TITLE
suggesting marketing resource

### PR DESCRIPTION
**Pull request by SaijoGeorge**
suggesting tldrmarketing as a resource

### CODE REVIEW

**Comment by gokulkrishh** [comment]
@SaijoGeorge hey, thanks for adding. But its not web development related right?

**Comment by SaijoGeorge** [comment]
No it's not.

**Comment by gokulkrishh** [comment]
Then we cannot add it here as this repo is only for web development related newsletters. But thanks for adding though.

**Comment by gokulkrishh** [comment]
Closing it for now. If you have any other web develpoment related newsletter which has quite good contents. We can add that.

**Pull request closed without merging**
